name: Android CI

on:
  push:
    branches: [ "workflows" ]
  pull_request:
    branches: [ "workflows" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      env:
        idea.paths.selector: "AndroidStudio"
      run: ./gradlew build
